const aporCodes = {
  'AG': 'Agribusiness & Agricultural Workers',
  'BA': 'Banks',
  'BP': 'BPOs & Export-Oriented Business Personnel',
  'CA': 'Civil Aviation',
  'CB': 'Customs Brokerage',
  'CM': 'Capital Market',
  'CY': 'Container Yards',
  'DC': 'Delivery personnel of cargoes',
  'DE': 'Delivery Services',
  'DO': 'Distressed OFWs',
  'DP': 'Delivery of Parcels',
  'DR': 'Disaster and Risk Reduction',
  'DS': 'Department of Labor and Employment - TUPAD',
  'EC': 'e-Commerce Companies',
  'EN': 'Energy Companies',
  'ER': 'Emergency Responders',
  'FC': 'Food Chain and Restaurants',
  'FF': 'Freight forwarders',
  'FS': 'Funeral Service',
  'GE': 'Government Agency - Executive',
  'GJ': 'Government Agency - Judicial',
  'GL': 'Government Agency - Legislative',
  'GR': 'Grocery and Convenience Stores',
  'HM': 'Heads of Mission',
  'HT': 'Hotel Employees and Tenants',
  'IP': 'International Passengers and Driver',
  'LW': 'Logistics Warehouse',
  'ME': 'Media Personalities',
  'MF': 'Manufacturing',
  'MS': 'Medical Services',
  'MT': 'Money Transfer Services',
  'NG': 'NGOs and other Humanitarian Assistance Personnel',
  'PC': 'Essential Public and Private Construction',
  'PH': 'Pharmacies and Drug Stores',
  'PI': 'Private Individual',
  'PM': 'Public Market',
  'PO': 'Port operators',
  'RE': 'Repairs and Installation of Machinery Equipment',
  'SA': 'Sanitation',
  'SB': 'Services to Buildings',
  'SH': 'Ship Captain & Crew',
  'SL': 'Shipping lines',
  'SO': 'Social Amelioration',
  'SS': 'Security Services',
  'TE': 'Telecommunications',
  'TF': 'Transportation Facilities',
  'TR': 'Transport and Traffic Management',
  'TS': 'Trucking Services',
  'UT': 'Utilities',
  'VE': 'Veterinary',
  'VO': 'Volunteer and Charitable Institutions',
  'WC': 'Water Companies',
  'WH': 'Warehousing',
  'WR': 'Water Refilling Stations'
};
